# Generated by Django 2.1.7 on 2019-03-22 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_workoutplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseTrack',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=50)),
                ('calorie_burnt_per_set', models.IntegerField(default=50)),
            ],
            options={
                'db_table': 'exercise_track',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlanDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sets', models.IntegerField(default=3)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ExerciseTrack')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.WorkoutPlan')),
            ],
            options={
                'db_table': 'workout_plan_details',
                'managed': True,
            },
        ),
    ]
