# Generated by Django 2.1.7 on 2019-03-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_exercisetrack_workoutplandetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_link', models.URLField(max_length=250)),
                ('blog_summary', models.CharField(max_length=400)),
                ('blog_title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'blogs',
                'managed': True,
            },
        ),
    ]
